all:
	gcc -o systemcalls_part1 systemcalls_part1.c && gcc -o systemcalls_part2 systemcalls_part2.c

part1: systemcalls_part1.c
	gcc systemcalls_part1.c -o systemcalls_part1

part2: systemcall_part2.c
	gcc systemcalls_part2.c -o systemcalls_part2

clean:
	rm -f *.o systemcalls_part1 systemcalls_part2
